In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\new folder\python310\lib\site-packages (2.3.3)

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: python-dateutil>=2.8.2 in c:\new folder\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in c:\new folder\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: pytz>=2020.1 in c:\new folder\python310\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\new folder\python310\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\new folder\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [4]:
#dataframe
#1. Create Dataframe
df = pd.DataFrame([11,22,33], columns=['Col_Name'])
print(df)

   Col_Name
0        11
1        22
2        33

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
data ={
     'Name' :['Niharika' , 'Anushka' , 'Suhani' , 'Pinky'],
     'Age'  :[16,17,20,21],
    'Salary': [40000, 50000,60000,24000]
}

In [7]:
df= pd.DataFrame(data)
print(df)

       Name  Age  Salary
0  Niharika   16   40000
1   Anushka   17   50000
2    Suhani   20   60000
3     Pinky   21   24000

In [ ]:
#2.Basic DATAFRAME UNDERSTANDING

In [8]:
df.head(2) # top rows

       Name  Age  Salary
0  Niharika   16   40000
1   Anushka   17   50000

In [9]:
df.tail(2)  #LAST ROWS

     Name  Age  Salary
2  Suhani   20   60000
3   Pinky   21   24000

In [10]:
df.shape

(4, 3)

In [11]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [12]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace= True)

In [13]:
df

       Name  Age  Monthly_Salary
0  Niharika   16           40000
1   Anushka   17           50000
2    Suhani   20           60000
3     Pinky   21           24000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes

In [15]:
df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   18.500000    43500.000000
std     2.380476    15351.438586
min    16.000000    24000.000000
25%    16.750000    36000.000000
50%    18.500000    45000.000000
75%    20.250000    52500.000000
max    21.000000    60000.000000

In [11]:
3. #Save and load data from CSV

In [16]:
df.to_csv('Test_data.csv', index=False)      #export dataframe

In [17]:
load_df = pd.read_csv('Test_data.csv')        #import dataframe
load_df

       Name  Age  Monthly_Salary
0  Niharika   16           40000
1   Anushka   17           50000
2    Suhani   20           60000
3     Pinky   21           24000

In [ ]:
#4. ROWS & COLUMNS SELECTION

In [18]:
#select column
df[['Name' , 'Monthly_Salary']]     #single column

       Name  Monthly_Salary
0  Niharika           40000
1   Anushka           50000
2    Suhani           60000
3     Pinky           24000

In [19]:
#select rows
#loc - index name based
df.loc[df.Name=='Niharika']
df.loc[(df.Name=='Niharika') & (df.Monthly_Salary>=20000)]

       Name  Age  Monthly_Salary
0  Niharika   16           40000

In [21]:
#iloc - index-value based 
df.iloc[0]
df.iloc[0:2]   [#start:stop:step]

SyntaxError: incomplete input (3048369348.py, line 3)

In [ ]:
#FILTER DATAFRAME

In [22]:
df

       Name  Age  Monthly_Salary
0  Niharika   16           40000
1   Anushka   17           50000
2    Suhani   20           60000
3     Pinky   21           24000

In [23]:
df_age_filter =df[df['Age']>18]

In [24]:
df_age_filter

     Name  Age  Monthly_Salary
2  Suhani   20           60000
3   Pinky   21           24000

In [25]:
df[(df['Age']>18) & (df['Monthly_Salary'] >= 10000)]

     Name  Age  Monthly_Salary
2  Suhani   20           60000
3   Pinky   21           24000

In [26]:
df.where(df['Age']>=18 , other = 'Not Eligible')

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        Suhani            20          60000
3         Pinky            21          24000

In [44]:
#6. ROWS AND COLUMNS - OPERATIONS (ADD,UPDATE , DELETE)

In [27]:
df

       Name  Age  Monthly_Salary
0  Niharika   16           40000
1   Anushka   17           50000
2    Suhani   20           60000
3     Pinky   21           24000

In [28]:
#add new column
df['Team'] = ['CEO' , 'HR' , 'CRM', 'CFO']
df

       Name  Age  Monthly_Salary Team
0  Niharika   16           40000  CEO
1   Anushka   17           50000   HR
2    Suhani   20           60000  CRM
3     Pinky   21           24000  CFO

In [29]:
df['Bonus'] = df['Monthly_Salary'] *0.2
df

       Name  Age  Monthly_Salary Team    Bonus
0  Niharika   16           40000  CEO   8000.0
1   Anushka   17           50000   HR  10000.0
2    Suhani   20           60000  CRM  12000.0
3     Pinky   21           24000  CFO   4800.0

In [30]:
df.loc[len(df)] = ['ABC' ,25 ,80000 , 'IT' , 2000]
df

       Name  Age  Monthly_Salary Team    Bonus
0  Niharika   16           40000  CEO   8000.0
1   Anushka   17           50000   HR  10000.0
2    Suhani   20           60000  CRM  12000.0
3     Pinky   21           24000  CFO   4800.0
4       ABC   25           80000   IT   2000.0

In [31]:
len(df)

5

In [32]:
#update value - using index name
df.loc[0, 'Monthly_Salary'] = 95000
df

       Name  Age  Monthly_Salary Team    Bonus
0  Niharika   16           95000  CEO   8000.0
1   Anushka   17           50000   HR  10000.0
2    Suhani   20           60000  CRM  12000.0
3     Pinky   21           24000  CFO   4800.0
4       ABC   25           80000   IT   2000.0

In [58]:
#update value - using column value
df.loc[df.Name== 'Pinky' , 'Monthly_Salary'] = 57000
df

       Name  Age  Monthly_Salary Team    Bonus
0  Niharika   16           95000  CEO   8000.0
1   Anushka   17           50000   HR  10000.0
2    Suhani   20           60000  CRM  12000.0
3     Pinky   21           57000  CFO   4800.0
4       ABC   25           80000   IT   2000.0
5       ABC   25           80000   IT   2000.0

In [ ]:
#delete value - row and column values

In [37]:
df = df.drop(df[df.Name == 'ABC'].index)   # drop row axis =0

In [34]:
df[df.Name == 'ABC']

  Name  Age  Monthly_Salary Team   Bonus
4  ABC   25           80000   IT  2000.0

In [35]:
df

       Name  Age  Monthly_Salary Team    Bonus
0  Niharika   16           95000  CEO   8000.0
1   Anushka   17           50000   HR  10000.0
2    Suhani   20           60000  CRM  12000.0
3     Pinky   21           24000  CFO   4800.0
4       ABC   25           80000   IT   2000.0

In [40]:
df.drop('Bonus' , axis=1 , inplace = True)  # drop column

In [41]:
df

       Name  Age  Monthly_Salary Team
0  Niharika   16           95000  CEO
1   Anushka   17           50000   HR
2    Suhani   20           60000  CRM
3     Pinky   21           24000  CFO

In [48]:
df.drop('Team' , axis=1 , inplace = True)   # drop multiple column

In [49]:
df

       Name  Age  Monthly_Salary
0  Niharika   16           95000
1   Anushka   17           50000
2    Suhani   20           60000
3     Pinky   21           24000

In [51]:
#value sort
df.sort_values('Monthly_Salary')

       Name  Age  Monthly_Salary
3     Pinky   21           24000
1   Anushka   17           50000
2    Suhani   20           60000
0  Niharika   16           95000

In [52]:
df.sort_values('Monthly_Salary' , ascending = False)  #descending order

       Name  Age  Monthly_Salary
0  Niharika   16           95000
2    Suhani   20           60000
1   Anushka   17           50000
3     Pinky   21           24000

In [ ]:
#7. WORKING WITH DATE VALUES

In [54]:
df['DOJ'] = ['2025-02-01' ,'2025-02-02', '2025-02-03','2025-02-04']
df

       Name  Age  Monthly_Salary         DOJ
0  Niharika   16           95000  2025-02-01
1   Anushka   17           50000  2025-02-02
2    Suhani   20           60000  2025-02-03
3     Pinky   21           24000  2025-02-04

In [56]:
df['DOJ'].dtype

dtype('O')

In [57]:
df['DOJ']= pd.to_datetime(df['DOJ'])

In [58]:
df

       Name  Age  Monthly_Salary        DOJ
0  Niharika   16           95000 2025-02-01
1   Anushka   17           50000 2025-02-02
2    Suhani   20           60000 2025-02-03
3     Pinky   21           24000 2025-02-04

In [59]:
df['DOJ'].dtype

dtype('<M8[ns]')

In [60]:
dg

NameError: name 'dg' is not defined

In [61]:
df

       Name  Age  Monthly_Salary        DOJ
0  Niharika   16           95000 2025-02-01
1   Anushka   17           50000 2025-02-02
2    Suhani   20           60000 2025-02-03
3     Pinky   21           24000 2025-02-04

In [63]:
#extract year , month , week , day
df['DOJ'].dt.year
#extarct month
df['DOJ'].dt.month
df['DOJ'].dt.day_name()

0    Saturday
1      Sunday
2      Monday
3     Tuesday
Name: DOJ, dtype: object

In [ ]:
#timedelta fucntion

In [ ]:
#8. HANDLING MISSING VALUES

In [65]:
df

       Name  Age  Monthly_Salary        DOJ
0  Niharika   16           95000 2025-02-01
1   Anushka   17           50000 2025-02-02
2    Suhani   20           60000 2025-02-03
3     Pinky   21           24000 2025-02-04

In [66]:
df.isnull()

    Name    Age  Monthly_Salary    DOJ
0  False  False           False  False
1  False  False           False  False
2  False  False           False  False
3  False  False           False  False

In [68]:
import numpy as np

In [69]:
df.loc[df.Name=='Niharika' , 'Monthly_Salary']= np.nan

In [70]:
df

       Name  Age  Monthly_Salary        DOJ
0  Niharika   16             NaN 2025-02-01
1   Anushka   17         50000.0 2025-02-02
2    Suhani   20         60000.0 2025-02-03
3     Pinky   21         24000.0 2025-02-04

In [71]:
df.isnull()

    Name    Age  Monthly_Salary    DOJ
0  False  False            True  False
1  False  False           False  False
2  False  False           False  False
3  False  False           False  False

In [72]:
df.isnull().sum()

Name              0
Age               0
Monthly_Salary    1
DOJ               0
dtype: int64

In [73]:
df.fillna(0)

       Name  Age  Monthly_Salary        DOJ
0  Niharika   16             0.0 2025-02-01
1   Anushka   17         50000.0 2025-02-02
2    Suhani   20         60000.0 2025-02-03
3     Pinky   21         24000.0 2025-02-04

In [ ]:
#9. AGGREGATION AND GROUP BY

In [74]:
df

       Name  Age  Monthly_Salary        DOJ
0  Niharika   16             NaN 2025-02-01
1   Anushka   17         50000.0 2025-02-02
2    Suhani   20         60000.0 2025-02-03
3     Pinky   21         24000.0 2025-02-04

In [78]:
df['Month'] = pd.to_datetime(df['DOJ']).dt.month
df[df['Month'] == 1].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
#group by

In [80]:
df.groupby('Month')['Monthly_Salary'].sum()    # aggregation based on group by

Month
2    134000.0
Name: Monthly_Salary, dtype: float64

In [82]:
df.groupby('Month').agg ({'Monthly_Salary' : 'mean', 'Name': 'count'})

       Monthly_Salary  Name
Month
2        44666.666667     4

In [ ]:
#10. CONCATENATE AND MERGE DATAFRAME (JOIN)

In [83]:
df1 = pd.DataFrame({'ID' : [1,2,3] , 'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [84]:
df2= pd.DataFrame({'ID' :[1,2,2,4], 'Score' :[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [85]:
pd.concat([df1,df2] , axis=0)  #vertical / row level join

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [86]:
pd.concat([df1,df2] , axis=1)  # horizontal / column

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [88]:
# merge - join
pd.merge(df1,df2 , how='inner', on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [89]:
pd.merge(df1,df2 , how='inner', left_on='ID' , right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [ ]:
pd.query()